import{sessions,postureRoutine}from'./program.js';import{loadState,saveState,migrateV1,importAnyObject}from'./storage.js';import{drawLine,e1rm}from'./charts.js';
let state=loadState();const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10);
function persist(){saveState(state);$('saveStatus').textContent='Guardado';$('saveStatus').className='pill ok'}function dirty(){$('saveStatus').textContent='Sin guardar';$('saveStatus').className='pill warn'}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$('view-'+name).classList.remove('hidden');document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='progress')renderProgress()}
function setupTabs(){document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>setView(b.dataset.view))}
function readiness(c){if(!c.sleep||!c.energy)return null;let s=70+(c.sleep-7)*8+(c.energy-7)*5-c.pain*4-(c.sportMinutes>=60?8:0);return Math.max(0,Math.min(100,Math.round(s)))}
function latestWeight(){return[...state.checkins].reverse().find(x=>x.weight)?.weight||[...state.logs].reverse().find(x=>x.weight)?.weight||null}
function renderDashboard(){$('todayText').textContent=new Intl.DateTimeFormat('es-PY',{dateStyle:'full'}).format(new Date());const last=state.checkins.at(-1),score=last?readiness(last):null;$('readinessScore').textContent=score??'—';$('currentWeight').textContent=latestWeight()??'—';const s=sessions[state.nextSession||'A'];$('nextSessionCard').innerHTML=`<h2>${s.name}</h2><p class="muted">${s.goal}</p>`}
function saveCheckin(){const c={date:$('dateInput').value,weight:+$('weightInput').value||null,sleep:+$('sleepInput').value||null,energy:+$('energyInput').value||null,pain:+$('painInput').value||null,sport:$('sportInput').value,sportMinutes:+$('sportMinutesInput').value||0,notes:$('notesInput').value,createdAt:new Date().toISOString()};state.checkins.push(c);persist();renderDashboard();alert('Control guardado')}
function renderWorkout(){const key=$('sessionSelect').value||state.nextSession||'A',s=sessions[key];$('sessionName').textContent=s.name;$('sessionGoal').textContent=s.goal;$('exerciseList').innerHTML=s.exercises.map((e,i)=>`<div class="exercise"><div class="exercise-head"><div><div class="exercise-title">${i+1}. ${e.name}</div><div class="target">${e.target}</div></div><span class="pill">${e.sets} series</span></div><div class="set-grid"><input id="load-${i}" type="number" step="0.1" value="${e.load}" placeholder="kg"><input id="reps-${i}" type="text" placeholder="Ej. 10-10-8"><input id="rir-${i}" type="number" min="0" max="5" placeholder="RIR"></div></div>`).join('')}
function saveWorkout(){const key=$('sessionSelect').value,s=sessions[key],exercises=s.exercises.map((e,i)=>({name:e.name,load:+$('load-'+i).value||0,reps:$('reps-'+i).value.trim(),rir:+$('rir-'+i).value||null})),c=state.checkins.at(-1);state.logs.push({date:$('dateInput').value||today(),weight:c?.weight||null,session:key,sessionName:s.name,exercises,createdAt:new Date().toISOString()});const order=['A','B','C','D'];state.nextSession=order[(order.indexOf(key)+1)%4];persist();renderDashboard();alert('Entrenamiento guardado')}
function renderPosture(){const date=$('dateInput').value||today(),done=state.posture.find(x=>x.date===date)?.done||[];$('postureList').innerHTML=postureRoutine.map(x=>`<label class="check-row"><span><strong style="font-size:16px">${x.name}</strong><br><span class="muted">${x.dose}</span></span><input type="checkbox" data-posture="${x.id}" ${done.includes(x.id)?'checked':''}></label>`).join('');updatePosturePercent();document.querySelectorAll('[data-posture]').forEach(x=>x.onchange=updatePosturePercent)}
function updatePosturePercent(){const c=[...document.querySelectorAll('[data-posture]')],done=c.filter(x=>x.checked).length;$('posturePercent').textContent=Math.round(done/c.length*100)+'%'}
function savePosture(){const date=$('dateInput').value||today(),done=[...document.querySelectorAll('[data-posture]:checked')].map(x=>x.dataset.posture);state.posture=state.posture.filter(x=>x.date!==date);state.posture.push({date,done});persist();alert('Rutina postural guardada')}
function renderHistory(){const rows=[...state.logs].reverse().slice(0,12);$('historyList').innerHTML=rows.length?rows.map(l=>`<div class="history-item"><strong style="font-size:16px">${l.date} · ${l.sessionName}</strong><div class="muted">${(l.exercises||[]).filter(e=>e.reps).slice(0,3).map(e=>`${e.name}: ${e.load} kg · ${e.reps}`).join('<br>')}</div></div>`).join(''):'<p class="muted">Todavía no hay entrenamientos.</p>'}
function renderProgress(){const weights=state.checkins.filter(x=>x.weight).map(x=>({v:x.weight,date:x.date}));drawLine($('weightChart'),weights,p=>`Último: ${p.v.toFixed(1)} kg`);const bench=[];state.logs.forEach(l=>{const ex=(l.exercises||[]).find(e=>/press banca/i.test(e.name));if(ex?.reps){const r=Math.max(...ex.reps.split('-').map(Number).filter(Boolean));bench.push({v:e1rm(ex.load,r),date:l.date})}});drawLine($('benchChart'),bench,p=>`1RM est.: ${p.v.toFixed(1)} kg`);renderHistory()}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportCSV(){const lines=['date,weight,session,exercise,load,reps,rir'];state.logs.forEach(l=>(l.exercises||[]).forEach(e=>lines.push([l.date,l.weight??'',l.session,`"${e.name}"`,e.load,`"${e.reps}"`,e.rir??''].join(','))));download('mf-performance.csv',lines.join('\n'),'text/csv')}
function runMigration(){const r=migrateV1(state);state=r.state;persist();$('migrationMessage').textContent=r.message;renderDashboard();renderHistory()}
function setup(){setupTabs();$('dateInput').value=today();$('sessionSelect').innerHTML=Object.entries(sessions).map(([k,s])=>`<option value="${k}">${s.name}</option>`).join('');$('sessionSelect').value=state.nextSession||'A';renderWorkout();renderDashboard();renderPosture();renderHistory();$('saveCheckinBtn').onclick=saveCheckin;$('goWorkoutBtn').onclick=()=>setView('workout');$('sessionSelect').onchange=renderWorkout;$('saveWorkoutBtn').onclick=saveWorkout;$('savePostureBtn').onclick=savePosture;$('runMigrationBtn').onclick=runMigration;$('exportJsonBtn').onclick=()=>download('mf-performance-backup.json',JSON.stringify(state,null,2),'application/json');$('exportCsvBtn').onclick=exportCSV;$('importJsonInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=importAnyObject(JSON.parse(r.result));persist();location.reload()}catch(x){alert('No se pudo importar: '+x.message)}};r.readAsText(f)};$('resetBtn').onclick=()=>{if(confirm('¿Borrar todos los datos locales de MF Performance?')){localStorage.removeItem('mfPerformanceV2');location.reload()}};document.addEventListener('input',dirty);if(!state.migratedFromV1)runMigration()}
setup();if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
